### ISSUE TITLE
Flutter road map

### ISSUE THREAD

**Issue by ebinantony08** [Ghanam330/FlutterRoadMap-ResourcesGuide#1]
# Flutter Roadmap

## Dart Basics
- [x] VARIABLES
    - [x] var
    - [x] dynamic
    - [x] int
    - [x] String
    - [x] double
    - [x] bool

- [x] FINAL AND CONST

- [x] STRINGS
    - [x] methods
    - [x] interpolation
    - [x] multi-line string
    - [x] raw string

- [x] LISTS
    - [x] List (Fixed and Growable)
    - [x] methods

- [x] MAPS
    - [x] Map (Fixed and Growable)
    - [x] methods

- [x] SETS
    - [x] Set ((Fixed and Growable)
    - [x] methods

- [x] FUNCTIONS
    - [x] Function as a variabl
    - [x] optional and required parameters
    - [x] fat arrow
    - [x] named parameters
    - [x] @required keyword
    - [x] positional parameters
    - [x] default parameter values
    - [x] Function as first-class objects
    - [x] Anonymous functions

- [ ] OPERATORS
    - [x] unary postfix expr++ expr — () [ ] . ?.
    - [x] unary prefix -expr !expr ~expr ++expr — expr await expr
    - [x] multiplicative * / % ~/
    - [x] additive + -
    - [x] shift << >> >>>
    - [x] bitwise AND &
    - [x] bitwise XOR ^
    - [x] bitwise OR |
    - [x] relational and type test >= > <= < as is is!
    - [x] equality == !=
    - [x] logical AND &&
    - [x] logical OR ||
    - [x] if null ??
    - [x] conditional expr1 ? expr2 : expr3
    - [x] cascade ..
    - [x] assignment = *= /= += -= &= ^= etc.

- [x] CONTROL FLOW STATEMENTS
    - [x] if and else
    - [x] for loops
    - [x] while and do-while
    - [x] break and continue
    - [x] switch and case
    - [ ] assert

- [x] EXCEPTIONS (ALL ARE UNCHECKED)
    - [x] Throw
    - [x] Catch
    - [x] on
    - [ ] rethrow
    - [ ] finally

- [x] CLASSES
    - [x] Class members
    - [x] Constructors
    - [x] Getting object type
    - [x] instance variables
    - [x] getters and setters
    - [x] Named constructors
    - [x] Initializer lists
    - [ ] Constant constructors
    - [ ] Redirecting constructors
    - [ ] Factory constructors
    - [ ] instance methods
    - [ ] abstract methods
    - [ ] abstract classes
    - [x] Inheritance
    - [x] Overriding
    - [ ] Overriding operators
    - [ ] noSuchMethod()
    - [ ] Extension methods
    - [x] Enums
    - [ ] Mixins (on keyword in mixins)
    - [x] Static keyword, static variables and methods

- [ ] LIBRARIES AND VISIBILITY
    - [ ] import
    - [ ] as
    - [ ] show
    - [ ] hide
    - [ ] deferred

- [ ] ASYNCHRONY SUPPORT
    - [x] Futures
    - [x] await
    - [x] async
    - [x] Streams
    - [ ] Stream methods

- [ ] OTHER TOPICS
    - [ ] Generators
    - [ ] Callable classes
    - [ ] Isolates
    - [ ] Typedefs
    - [ ] Metadata
    - [ ] Custom annotation
    - [ ] Comments, Single-line comments, Multi-line comments, Documentation comments

- [ ] OTHER KEYWORDS FUNCTIONS
    - [ ] covariant
    - [ ] export
    - [ ] external
    - [ ] part
    - [ ] sync
    - [ ] yield

## Flutter 

- [x] BASICS

    - [x] MaterialApp
    - [x] Scaffold
    - [x] AppBar
    - [x] Container
    - [x] Icon
    - [x] Image
    - [x] PlaceHolder
    - [x] ElevatedButton
    - [x] Text
    - [x] RichText

- [x] STATELESS AND STATEFULWIDGETS

    - [x] Differences
    - [x] When To Use?
    - [x] How To Use?

- [x] INPUT

    - [x] Form
    - [x] Form Field
    - [x] Text Field
    - [x] TextEditing Controller
    - [ ] Focus Node

- [x] LAYOUTS

    - [x] Align
    - [x] Aspect Ratio
    - [x] Baseline
    - [x] Center
    - [x] Constrained Box
    - [x] Container
    - [x] Expanded
    - [x] Fitted Box
    - [x] FractionallySizedBox
    - [x] Intrinsic Height
    - [x] Intrinsic Width
    - [x] Limited Box
    - [x] Overflow Box
    - [x] Padding
    - [x] Sized Box
    - [ ] SizedOverflowBox
    - [ ] Transform
    - [x] Column
    - [x] Flow
    - [x] Grid View
    - [ ] Indexed Stack
    - [ ] Layout Builder
    - [x] List Body
    - [x] List View
    - [x] Row
    - [x] Stack
    - [x] Table
    - [x] Wrap
    - [x] Safe Area

- [x] MATERIAL COMPONENTS

    - [x] App bar
    - [x] Bottom Navigation Bar
    - [x] Drawer
    - [x] Material App
    - [x] Scaffold
    - [x] SliverAppBar
    - [x] TabBar
    - [x] TabBarView
    - [x] WidgetsApp

- [x] NAVIGATOR

    - [x] pop
    - [x] Routes
    - [x] Bottom Navigation
    - [x] Drawer
    - [x] Create Multipage App
    - [ ] popUntil
    - [ ] canPop
    - [x] push
    - [x] pushNamed
    - [ ] popAndPushNamed
    - [x] replace
    - [ ] pushAndRemoveUntil
    - [ ] NavigatorObserver
    - [ ] MaterialRouteBuilder

- [x] BUTTONS

    - [x] ButtonBar
    - [x] DropdownButton
    - [x] ElevatedButton
    - [x] FloatingActionButton
    - [x] IconButton
    - [x] OutlineButton
    - [x] PopupMenuButton
 

- [ ] INPUT AND SELECTIONS

    - [x] Checkbox
    - [x] Date & Time Pickers
    - [ ] Radio
    - [ ] Slider
    - [ ] Switch

- [x] DIALOGS, ALERTS, AND PANELS

    - [x] AlertDialog
    - [x] BottomSheet
    - [x] ExpansionPanel
    - [ ] SimpleDialog
    - [x] SnackBar
    - [ ] SearchDelegate

- [x] INFORMATION DISPLAYS

    - [x] Card
    - [ ] Chip
    - [x] CircularProgressIndicator
    - [ ] DataTable
    - [ ] LinearProgressIndicator
    - [ ] Tooltip

- [ ] LAYOUT

    - [x] Divider
    - [x] ListTile
    - [ ] Stepper

- [ ] SCROLLING

    - [x] CustomScrollView
    - [ ] NestedScrollView
    - [ ] NotificationListener
    - [x] PageView
    - [ ] RefreshIndicator
    - [ ] ScrollConfiguration
    - [ ] Scrollable
    - [ ] Scrollbar
    - [x] SingleChildScrollView

- [x] OTHER USEFUL WIDGETS

    - [x] MediaQuery
    - [ ] LayoutBuilder
    - [ ] OrientationBuilder
    - [x] FutureBuilder
    - [x] StreamBuilder
    - [ ] DraggableScrollableSheet

- [ ] CUPERTINO (IOS-STYLE) WIDGETS

    - [ ] CupertinoActionSheet
    - [ ] CupertinoActivityIndicator
    - [ ] CupertinoAlertDialog
    - [ ] CupertinoButton
    - [ ] CupertinoContextMenu
    - [ ] CupertinoDatePicker
    - [ ] CupertinoDialog
    - [ ] CupertinoDialogAction
    - [ ] CupertinoNavigationBar
    - [ ] CupertinoPageScaffold
    - [ ] CupertinoPicker
    - [ ] CupertinoPageTransition
    - [ ] CupertinoScrollbar
    - [ ] CupertinoSegmentedControl
    - [ ] CupertinoSlider
    - [ ] CupertinoSlidingSegmentedControl
    - [ ] CupertinoSwitch
    - [ ] CupertinoTabBar
    - [ ] CupertinoTabScaffold
    - [ ] CupertinoTabView
    - [ ] CupertinoTextField
    - [ ] CupertinoTimerPicker

- [ ] ANIMATIONS

    - [ ] Ticker
    - [ ] Animation
    - [ ] AnimationController
    - [ ] Tween animation
    - [ ] Physics-based animation
    - [ ] AnimatedWidget
    - [ ] AnimatedBuilder
    - [ ] AnimatedContainer
    - [ ] AnimatedOpacity
    - [ ] AnimatedSize
    - [ ] FadeTransition
    - [ ] Hero
    - [ ] RotationTransition
    - [ ] ScaleTransition
    - [ ] SizeTransition
    - [ ] SlideTransition

- [ ] NETWORKING

    - [x] http, dio libraries
    - [x] json parsing

- [ ] Local Persistent Storage

    - [ ] SQFLITE
    - [ ] Shared Preferences
    - [x] Hive
    - [ ] JSON
    - [ ] JSON- PARSING

- [ ] INTERNATIONALI ZING FLUTTER APPS

    - [ ] Locale
    - [ ] AppLocalization
    - [ ] json files

- [ ] STATE MANAGEMENT

    - [x] setState
    - [x] InheritedWidget
    - [ ] ScopedModel
    - [ ] Provider
    - [ ] Redux
    - [ ] BLOC

- [ ] OTHER IMPORTANT TOPICS

    - [ ] Widget Tree, Element Tree and Render Tree
    - [ ] App Lifecycle
    - [ ] Dynamic Theming
    - [ ] Flare
    - [ ] Overlay widget
    - [ ] Visibility Widget
    - [ ] Spacer Widget
    - [ ] Universal error
    - [ ] Search Layout
    - [ ] CustomPainter
    - [ ] WidgetsBindingObserver
    - [ ] RouteObserver
    - [ ] SystemChrome
    - [ ] Internet connectivity
    - [ ] Http Interceptor
    - [ ] Google Map
    - [x] Firebase Auth
    - [ ] Cloud FireStore DB
    - [ ] Real time DB
    - [x] File/Image Upload
    - [x] Firebase database
    - [x] Firestore
    - [ ] Semantic versioning
    - [ ] Finding size and position of widget using RenderObject
    - [x] Building release APK
    - [ ] Publishing APK on Play Store
    - [ ] RxDart

- [ ] TESTING AND DEBUGGING

    - [x] Debugging
    - [ ] Unit Testing
    - [ ] UI (Widget) Testing
    - [ ] Integration Testing

**Comment by ebinantony08** [comment]
aa

**Comment by ebinantony08** [comment]
eqfw

**Comment by ebinantony08** [comment]
close
